name: Small docs fix (typo/clarity)
description: Report a typo, grammar fix, or tiny content tweak
labels: ["docs"]
body:
  - type: input
    id: page
    attributes:
      label: Page URL
      placeholder: https://squidacademy.mintlify.app/...
  - type: textarea
    id: current
    attributes:
      label: Current text
      placeholder: Paste the exact text you see now
  - type: textarea
    id: suggestion
    attributes:
      label: Suggested change
      placeholder: Paste your corrected version
